### ISSUE TITLE
Add sanity check for the number of generated records for each library

### ISSUE THREAD

**Issue by ashtum** [cppalliance/boost-gecko#88]
We should not anticipate a significant variation in the number of generated records for each library between consecutive releases. For instance, if Asio version 1.82.0 has 10254 search records, observing a count of 9,000 or 15,000 records in version 1.83.0 might indicate a potential issue with the crawler and should be further investigated.

We can include the expected numbers in the configuration, as follows:

```Yaml
libraries:
  - key: asio
    exp-records: 10254
    exp-words: 941387

  - key: bimap
    exp-records: 168
    exp-words: 44906
```

We will extract these numbers from the generated records, and since they can change gradually, we will update them with each Boost release.
